run:
Welcome to rock-paper-scissor game ,you will play 5 matches with system ,one with most wins will
1-rock , 2-paper and 3-scissor
2
The system chose paper!!!
It is a tie , You both chose paper , play again
1-rock , 2-paper and 3-scissor
1
The system chose rock!!!
 It is a tie , You both chose rock , play again
1-rock , 2-paper and 3-scissor
3
The system chose scissor!!!
It is a tie , You both chose scissor , play again
1-rock , 2-paper and 3-scissor
2
The system chose rock!!!
You chose paper , paper beats rock!!!!, you win!!!
1-rock , 2-paper and 3-scissor
1
The system chose rock!!!
 It is a tie , You both chose rock , play again
You had1 wins ,YOU WON!!!!!!!
BUILD SUCCESSFUL (total time: 11 seconds)
